name: build
on:
  push:
    branches:
    - master
permissions:
  contents: write
  id-token: write
  pages: write
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  Compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - name: src/plugins/rules/aktest
        - name: src/plugins/rules/hstest
        - name: src/plugins/rules/rttest
        - name: src/plugins/rules/tmtest
        - name: src/plugins/rules/yltest
        - name: src/plugins/utils/format
        - name: src/plugins/utils/latest
        - name: src/plugins/utils/maplot
        - name: src/plugins/utils/prefix
    steps:
    - uses: nextzlog/zylo@master
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        version: 2.8.3.0
        directory: ${{matrix.name}}
  Prepare:
    needs: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'
    - uses: actions/checkout@v4
      with:
        path: zylo
    - uses: actions/checkout@v4
      with:
        path: zlog
        repository: jr8ppg/zlog
    - run: |
        mkdir -p _includes
        cp ${GITHUB_WORKSPACE}/zlog/zlog/main.dfm _includes
        grep object _includes/main.dfm > _includes/form.dfm
        cp $GITHUB_WORKSPACE/zylo/README.md _includes/
      working-directory: zylo/src/manuals
    - name: publish manuals
      run: |
        go install github.com/robertkrimen/godocdown/godocdown@latest
        godocdown -o _reiwa.md -template manuals/_reiwa.md commons/reiwa
        godocdown -o _win32.md -template manuals/_win32.md commons/win32
        cat _*.md >> manuals/index.md
      working-directory: zylo/src
    - uses: actions/configure-pages@v5
    - uses: actions/jekyll-build-pages@v1
      with:
        source: zylo/src/manuals
    - uses: actions/upload-pages-artifact@v3
  Publish:
    needs: Prepare
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
    - uses: actions/deploy-pages@v4
